import { AuthUser, Record } from '../types';

export const MOCK_USERS: (AuthUser & { password: string })[] = [
  {
    id: 'admin-001',
    name: 'Diganta Admin',
    email: 'admin@app.com',
    password: 'admin123',
    role: 'admin',
    avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=admin',
  },
  {
    id: 'user-001',
    name: 'Diganta User',
    email: 'user@app.com',
    password: 'user123',
    role: 'user',
    avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=user1',
  },
  {
    id: 'user-002',
    name: 'Priya Sharma',
    email: 'priya@app.com',
    password: 'user123',
    role: 'user',
    avatar: 'https://api.dicebear.com/8.x/bottts/svg?seed=priya',
  },
];

export const MOCK_RECORDS: Record[] = [
  {
    id: 'rec-001',
    title: 'Complete API Integration',
    description: 'Integrate the REST API endpoints for user management module. Need to handle authentication tokens and refresh logic.',
    category: 'work',
    status: 'active',
    ownerId: 'user-001',
    ownerName: 'Diganta User',
    createdAt: '2025-04-01T10:00:00.000Z',
    updatedAt: '2025-04-10T14:30:00.000Z',
  },
  {
    id: 'rec-002',
    title: 'Design System Update',
    description: 'Update the design system with new color tokens and typography scales. Include dark mode variants for all components.',
    category: 'work',
    status: 'completed',
    ownerId: 'user-001',
    ownerName: 'Diganta User',
    createdAt: '2025-03-15T09:00:00.000Z',
    updatedAt: '2025-04-05T16:00:00.000Z',
  },
  {
    id: 'rec-003',
    title: 'Grocery Shopping List',
    description: 'Weekly grocery run — vegetables, fruits, dairy products, and cleaning supplies. Check pantry before going.',
    category: 'personal',
    status: 'active',
    ownerId: 'user-001',
    ownerName: 'Diganta User',
    createdAt: '2025-04-12T07:00:00.000Z',
    updatedAt: '2025-04-12T07:00:00.000Z',
  },
  {
    id: 'rec-004',
    title: 'Fix Production Bug #1234',
    description: 'Critical bug in payment processing module causing transaction failures for international cards. Needs immediate attention.',
    category: 'urgent',
    status: 'active',
    ownerId: 'user-002',
    ownerName: 'Priya Sharma',
    createdAt: '2025-04-13T08:00:00.000Z',
    updatedAt: '2025-04-13T08:00:00.000Z',
  },
  {
    id: 'rec-005',
    title: 'Team Meeting Notes',
    description: 'Prepare and distribute meeting notes from the quarterly planning session. Include action items and deadlines.',
    category: 'work',
    status: 'completed',
    ownerId: 'user-002',
    ownerName: 'Priya Sharma',
    createdAt: '2025-03-20T11:00:00.000Z',
    updatedAt: '2025-04-01T09:00:00.000Z',
  },
  {
    id: 'rec-006',
    title: 'Book Doctor Appointment',
    description: 'Schedule annual health checkup. Need to book blood work and general physical examination.',
    category: 'personal',
    status: 'archived',
    ownerId: 'user-002',
    ownerName: 'Priya Sharma',
    createdAt: '2025-02-10T08:00:00.000Z',
    updatedAt: '2025-03-15T10:00:00.000Z',
  },
  {
    id: 'rec-007',
    title: 'Security Audit Report',
    description: 'Compile security audit findings and prepare remediation plan. Deadline is end of this sprint.',
    category: 'urgent',
    status: 'active',
    ownerId: 'admin-001',
    ownerName: 'Diganta Admin',
    createdAt: '2025-04-11T09:00:00.000Z',
    updatedAt: '2025-04-14T12:00:00.000Z',
  },
  {
    id: 'rec-008',
    title: 'Update Documentation',
    description: 'Refresh API documentation with new endpoints added in v2.3 release. Include request/response examples.',
    category: 'other',
    status: 'active',
    ownerId: 'admin-001',
    ownerName: 'Diganta Admin',
    createdAt: '2025-04-08T10:00:00.000Z',
    updatedAt: '2025-04-12T15:00:00.000Z',
  },
  {
    id: 'rec-009',
    title: 'Yoga Class Registration',
    description: 'Sign up for the weekend yoga class at the community center. Morning batch preferred.',
    category: 'personal',
    status: 'completed',
    ownerId: 'user-001',
    ownerName: 'Diganta User',
    createdAt: '2025-03-25T06:00:00.000Z',
    updatedAt: '2025-04-02T07:00:00.000Z',
  },
  {
    id: 'rec-010',
    title: 'Client Presentation Prep',
    description: 'Prepare slide deck for the Q2 client review. Include performance metrics, roadmap updates, and budget forecast.',
    category: 'work',
    status: 'active',
    ownerId: 'user-002',
    ownerName: 'Priya Sharma',
    createdAt: '2025-04-14T08:00:00.000Z',
    updatedAt: '2025-04-14T08:00:00.000Z',
  },
];
